obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.127, -0.2223], [0.127, 0.2223], [-0.4475, 0.2223], [-0.4475, -0.2223]]
footprint: [[0.15, 0.2191], [0.15, -0.2191], [-0.4205, -0.2191], [-0.4205, 0.2191]]
#footprint: [[0.1524, 0.2191], [0.1524, -0.2191], [-0.4205, -0.2191], [-0.4205, 0.2191]]

#robot_radius: ir_of_robot
inflation_radius: 0.00
obstacle_layer:
  observation_sources: laser_scan_sensor

  laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}